// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CheckFFmpeg():Promise<boolean>;

export function ConvertFiles(arg1:models.BatchConversionRequest):Promise<models.BatchConversionResult>;

export function GetAppInfo():Promise<Record<string, string>>;

export function GetConversionHistory(arg1:number):Promise<Array<models.Conversion>>;

export function GetFFmpegVersion():Promise<string>;

export function GetOutputFormats(arg1:string):Promise<Array<string>>;

export function GetSettings():Promise<models.UserSettings>;

export function SaveSettings(arg1:models.UserSettings):Promise<void>;

export function SelectDirectory():Promise<string>;

export function SelectFiles():Promise<Array<models.FileInfo>>;
