// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckFFmpeg() {
  return window['go']['main']['App']['CheckFFmpeg']();
}

export function ConvertFiles(arg1) {
  return window['go']['main']['App']['ConvertFiles'](arg1);
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetConversionHistory(arg1) {
  return window['go']['main']['App']['GetConversionHistory'](arg1);
}

export function GetFFmpegVersion() {
  return window['go']['main']['App']['GetFFmpegVersion']();
}

export function GetOutputFormats(arg1) {
  return window['go']['main']['App']['GetOutputFormats'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectFiles() {
  return window['go']['main']['App']['SelectFiles']();
}
